swagger: "2.0"
info:
  description: "This is the list of API methods supported for Our Places"
  version: "1.0.0"
  title: "Our Places API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pavelbyles@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "pb5.io"
basePath: "/v1"
tags:
- name: "place"
  description: "Everything about the places"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /place:
    post:
      tags:
      - "place"
      summary: "Add a new place"
      description: ""
      operationId: "addPlace"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Place object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Place"
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "place"
      summary: "Gets the list of all places"
      description: ""
      operationId: "getPlaces"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "per_page"
        schema:
          type: "integer"
        required: false
        description: Maximum number of results to return, the default is 10.
      responses:
        200:
          description: "List of places"
      - in: "query"
        name: page
        schema:
          type: "integer"
        required: false
        description: The page of results to return.  The default is the first page
    put:
      tags:
      - "place"
      summary: "Update an existing place"
      description: ""
      operationId: "updatePlace"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Place object that needs to be updated in the database"
        required: true
        schema:
          $ref: "#/definitions/Place"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Place not found"
        405:
          description: "Validation exception"
  /place/{placeId}:
    get:
      tags:
      - "place"
      summary: "Find place by ID"
      description: "Returns a single place"
      operationId: "getPlaceById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "placeId"
        in: "path"
        description: "ID of place to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Place"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Place not found"
definitions:
  Place:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "My Villa"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "Place status"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Place"
  Tag:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "apartment"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
