service: frontend
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
- url: /bower_components
  static_dir: bower_components
- url: /images
  static_dir: images
- url: /src
  static_dir: src
